---
name: CI
on: 
  push: 
    branches: 
      - "main"
      - "master"
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4
        
      - name: Install Nix
        if: ${{ !env.ACT }}
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Resume with Nix
        if: ${{ !env.ACT }}
        run: |
          nix build --print-build-logs
          cp result/resume.pdf Maharshi_Basu_Resume.pdf
          
      - name: Release PDF
        uses: softprops/action-gh-release@v2  # Updated to v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Maharshi_Basu_Resume.pdf
          name: Maharshi_Basu_Resume.pdf
    
      - name: Make a pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: Maharshi_Basu_Resume.pdf
          
      - name: Install Poppler
        if: ${{ !env.ACT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          
      - name: Convert PDF to PNG
        if: ${{ !env.ACT }}
        run: |
          echo "Starting PDF to PNG conversion..."
          if [ -f Maharshi_Basu_Resume.png ]; then  # Fixed syntax
            rm Maharshi_Basu_Resume.png
            echo "Removed existing PNG files"
          fi
          pdftoppm -png -r 300 -cropbox Maharshi_Basu_Resume.pdf Maharshi_Basu_Resume
          echo "Generated files: "
          ls -la Maharshi_Basu_Resume-*.png

          sudo apt install -y imagemagick
          echo "Checking for multiple pages..."
          if [ -f Maharshi_Basu_Resume-2.png ]; then
            echo "Found 2 pages, concatenating..."
            echo "Page 1 size:" && identify Maharshi_Basu_Resume-1.png
            echo "Page 2 size:" && identify Maharshi_Basu_Resume-2.png
            convert Maharshi_Basu_Resume-1.png Maharshi_Basu_Resume-2.png -append Maharshi_Basu_Resume.png
            echo "Final concatenated image:" && identify Maharshi_Basu_Resume.png
            echo "Cleaned up individual page files"
            rm Maharshi_Basu_Resume-1.png Maharshi_Basu_Resume-2.png
          else
            echo "Only 1 page found, renaming..."
            mv Maharshi_Basu_Resume-1.png Maharshi_Basu_Resume.png
          fi
          echo "Final PNG file info:"
          ls -la Maharshi_Basu_Resume.png

      - name: Add resume to readme
        if: ${{ !env.ACT }}
        run: |
          TIMESTAMP=$(data +s%)
          cat > README.md << 'EOF'
          ![Resume](Maharshi_Basu_Resume.png?v=TIMESTAMP_PLACEHOLDER)
          EOF
          sed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/" README.md
          echo "Created README.md"
          
      - name: Check for changes
        id: check_changes
        run: |
          git add Maharshi_Basu_Resume.png Maharshi_Basu_Resume.pdf README.md
          if [[ -n $(git status -s) ]]; then
            echo "Changes detected. Committing and pushing..."
            echo "change=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected. Skipping commit and push."
            echo "change=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check_changes.outputs.change == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add PNG and PDF + Update README"
          git push